### ISSUE TITLE
Describe relationship to DistKV

### ISSUE THREAD

**Issue by bkanuka** [M-o-a-T/distmqtt#1]
Could you please describe the relationship between DistMQTT and DistKV?

- Is DistKV required to use DistMQTT?
- What features does DistKV add to this project or MQTT in general?
- Why did you make the decision to couple a DistKV client and MQTT client together?

I'm asking because while I generally like the idea of anyio hbmqtt library, I don't think I need DistKV for my project.

**Comment by smurfix** [comment]
No. You can safely ignore it and I'll modify things to support that better soon(ish).

Distributed master-less persistence, and support for server-side data translation. (MQTT wants "ON" and "OFF" or whatever, while when you use DistKV you can just use Python data types directly.)

I didn't; the MQTT *server* acts as a DistKV client / gateway.
